### PR TITLE
fix(compiler): be less clever about generating aliases

### LINKED ISSUE #5708: bug: `CompileError: Multiple, unrelated CTEs` on union of complex Tables
### What happened?

```python
import ibis
from ibis import _
from ibis import examples as ex

t1 = ex.Aids2.fetch()
t2 = ex.Aids2.fetch()
cols = ["diag", "status"]
t1 = t1.select(*cols)
t2 = t2.select(*cols)
t1 = t1.mutate(diag = _.diag + 1)
t2 = t2.mutate(diag = _.diag + 1)
t1 = t1.mutate(diag=_.diag.cast("int32"))
t2 = t2.mutate(diag=_.diag.cast("int32"))
u = ibis.union(t1, t2)
u.execute()
```

Results in `CompileError: Multiple, unrelated CTEs found with the same name: 't0'`

If I skip one of these modifications, it does not error. If I re-order them, then it still errors.

This appears way too down in the guts of Ibis for me to want to tackle myself, sorry :)

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

duckdb

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cpcloud**
Fixes an issue where we were generating duplicate aliases.

Fixes #5708.

### CODE REVIEW

**Comment by cpcloud** [comment]
Cloud backends look good:

```
…/ibis on  union-aliasing-bug is 📦 v4.1.0 via 🐍 v3.11.2 via ❄️  impure (ibis-3.11.2-env)
❯ pytest -m 'snowflake or bigquery' -n auto -q --dist loadgroup --snapshot-update
bringing up nodes...
xxxxxxx........x..x.................x...........x..xxx.xx............x..xx.......x..xx.x.....x............x......x.xxx.xxx.........x..x....x.x..x.xx.xx..x.xx...xx.x.xx..x.x..xx...x...x..x... [  9%]
..xx..xxxx....xx.....x...x......x..x...........x.x......................x.....................x..x....................................x.........................xx..x........xx..x....x....... [ 18%]
...x.............xxxx.xxxxxxxxx...x..xx.xx...xxxx.x..x.x..xx.....x....x.............x.x.....x...........x.x....x.....xx.xx...xx.x..xxx.......x..x.....x..x.......xxx...x.x.x....x.....x....... [ 28%]
......xx.......x...xx........x...x.x.x........................x.x.....x..x..x..x..xx.x...x.x.x...xxxxxxxxxxxx.xx...........x.x.x.........x.x.......x................................x........x [ 37%]
....x........x............x.x..............x..........................................................x........x..x..x...x......x..xx..x.x..x.x..x.x......x.........x......................... [ 47%]
...x....x.x.x..x..xx.....xx....x...........x...x..xx...x..x..x.xxx..x..x........x.x...x.xx...........xxx..........xx..x.xx.x.xx.x......x.xx..xx....xxx...x.................x.................. [ 56%]
...x..............................................................xx.........x.x.xxx.......x.xx...xx.....x.x..........xx..............x..x..x..................x.............................. [ 66%]
.........x.x.....x.x...x..........x...x...............................x.......x.........s.......x.............x..x.x...x....x.........................x.......s..........s...x........s....x.. [ 75%]
xxxx...xxxxxxxxx..x........xxx......x..x..x..................x....x..........................xx.....x......x....................x..x.............x.......x...x.xx..................x........... [ 84%]
.............................................x.............................................................................x........x.xx.xxx........................x..................x..x... [ 94%]
........................................x...........ss...s..s......xsx......x.........x..s.s.............x.....                                                                                [100%]
1659 passed, 11 skipped, 342 xfailed in 173.51s (0:02:53)
```

File: ibis/backends/bigquery/tests/system/snapshots/test_client/test_cross_project_query/out.sql [hunk 1]
```diff
@@ -1,6 +1,6 @@
 SELECT t0.`title`, t0.`tags`
 FROM (
-  SELECT t1.*
-  FROM `bigquery-public-data.stackoverflow.posts_questions` t1
-  WHERE STRPOS(t1.`tags`, 'ibis') - 1 >= 0
+  SELECT t2.*
+  FROM `bigquery-public-data.stackoverflow.posts_questions` t2
+  WHERE STRPOS(t2.`tags`, 'ibis') - 1 >= 0
```
Comment (gforsyth) [inline ibis/backends/bigquery/tests/system/snapshots/test_client/test_cross_project_query/out.sql:5]: does this indicate that we're generating an intermediary alias and then dropping it along the way?

**Review by gforsyth — APPROVED** [review]
I'm all for less cleverness -- one comment on some of the generated SQL.  Definitely non-blocking.

File: ibis/backends/bigquery/tests/system/snapshots/test_client/test_cross_project_query/out.sql (hunk 1 above)
Comment (cpcloud) [reply ibis/backends/bigquery/tests/system/snapshots/test_client/test_cross_project_query/out.sql:5]: It's possible the +1 on the parent isn't necessary, let me check.

Comment (cpcloud) [reply ibis/backends/bigquery/tests/system/snapshots/test_client/test_cross_project_query/out.sql:5]: Looks like that isn't needed, since `make_alias` leaves the `_alias_counter` at the value of the *next* alias.

Comment (cpcloud) [reply ibis/backends/bigquery/tests/system/snapshots/test_client/test_cross_project_query/out.sql:5]: Which means the number of regenerated files should decrease!

File: ibis/tests/sql/snapshots/test_sqlalchemy/test_no_cross_join/out.sql [hunk 2]
```diff
@@ -1,15 +1,15 @@
...
+  t3.personal,
+  t3.family,
+  t4.taken,
+  t4.person,
+  t4.quant,
+  t4.reading,
   t2.id AS id_y,
   t2.site,
   t2.dated
-FROM person AS t0
```
[the remark this answers is not in the document]
Comment (cpcloud) [reply ibis/tests/sql/snapshots/test_sqlalchemy/test_no_cross_join/out.sql]: Ok, this should be fixed now. The issue was that we still need to look up references to tables, using the parent context in case we're referring to them in a child context.

[the remark this answers is not in the document]
Comment (gforsyth) [reply ibis/tests/sql/snapshots/test_sqlalchemy/test_no_cross_join/out.sql]: Down to 11 files changed!

**Review by gforsyth — APPROVED** [review]
nice!  may we all strive to be less clever.
