### PR TITLE
fix(deps): bump sqlglot to pick up duckdb array fixes

### LINKED ISSUE #8641: bug: array(literal).zip() errors
### What happened?

```python
import ibis

a = ibis.array([1, 2, 3])
z = a.zip(a)
z
```

causes `ParserException: Parser Error: syntax error at or near "["`

If I inspect the sql (ibis.to_sql() also errors, that could be a nice little ux improvement), then I think it is related to https://github.com/duckdb/duckdb/issues/11120

```sql
SELECT
  LIST_APPLY(
    RANGE(
      1,
      GREATEST(
        LENGTH([CAST(1 AS TINYINT), CAST(2 AS TINYINT), CAST(3 AS TINYINT)]),
        LENGTH([CAST(1 AS TINYINT), CAST(2 AS TINYINT), CAST(3 AS TINYINT)])
      ) + 1
    ),
    i -> {'f1': [CAST(1 AS TINYINT), CAST(2 AS TINYINT), CAST(3 AS TINYINT)][i], 'f2': [CAST(1 AS TINYINT), CAST(2 AS TINYINT), CAST(3 AS TINYINT)][i]}
  ) AS "ArrayZip()"
```

Perhaps we could generate list literals with `list_value(a, b, c)` syntax instead of `[a,b,c]` syntax as a workaround?

### What version of ibis are you using?

main

### What backend(s) are you using, if any?

duckdb

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cpcloud**
Closes #8641. The fix was made upstream in sqlglot.

This PR ballooned into some other fixes:

1. We're segfaulting a lot because of duckdb/duckdb_spatial#236. I removed geospatial tests from the duckdb 0.10 CI job and added a 0.9.2 job that should mitigate this until the next duckdb geospatial release.
2. The sqlglot version bump introduced some changed SQL, so I updated the snapshots for that
3. The sqlglot verison bump changed mssql limit output to use `fetch` instead of `top`, which breaks the case of `limit 0`. `fetch first 0 rows only` raises a DB error, while `top 0` is allowed. I elected to xfail this for now but perhaps we should raise an issue on the sqlglot side?
4. Because of the sqlglot bump, log function calls are now generated using `log(x, y)` (base first or not depends on the dialect) without explicitly constructing an `Anonymous` function using `self.f.anon`. This exposed a missing `log` implementation in the sqlite backend which I added.
5. I addressed the failing `test_zip_null` test that was failing for the cloud backends. BigQuery xfails with an AssertionError because it turns NULL arrays into empty arrays and the fix for snowflake was to check for any NULL input arrays and return NULL accordingly.

### CODE REVIEW

**Comment by cpcloud** [comment]
I've remove geospatial from the primary duckdb ci job and added another job that runs geospatial tests while constraining the install of duckdb to be <0.10. This should avoid segfaulting in CI, and once duckdb/duckdb_spatial ships a new release we can go back to testing just one version of duckdb.

**Review by kszucs — APPROVED** [review]

File: ibis/backends/tests/snapshots/test_sql/test_isin_bug/clickhouse/out.sql [hunk 1]
```diff
@@ -1,9 +1,7 @@
 SELECT
-  "t0"."x" IN (
-    SELECT
-      "t0"."x"
-    FROM "t" AS "t0"
-    WHERE
-      "t0"."x" > 2
-  ) AS "InSubquery(x)"
+  "t0"."x" IN (SELECT
```
[the remark this answers is not in the document]
Comment (kszucs) [reply ibis/backends/tests/snapshots/test_sql/test_isin_bug/clickhouse/out.sql:2]: Turns out this is not caused by the sqlglot version bump.

File: ibis/backends/__init__.py [hunk 2]
```diff
@@ -926,8 +926,8 @@ def compile(
         """Compile an expression."""
         return self.compiler.to_sql(expr, params=params)
 
-    def _to_sql(self, expr: ir.Expr, **kwargs) -> str:
```
Comment (kszucs) [inline ibis/backends/__init__.py:929]: There are still 2 occurencies where `_to_sql` is used:

```
❯ rg "\._to_sql\("
ibis/backends/duckdb/__init__.py
1374:        query = self._to_sql(expr, params=params)
1410:        query = self._to_sql(expr, params=params)
```

These should be removed in favor of `self.compile()`

Comment (kszucs) [reply ibis/backends/__init__.py:929]: Also `_to_sql()` is defined at 3 other places:

```
❯ rg "def _to_sql\("
ibis/tests/expr/mocks.py
56:    def _to_sql(self, expr, **kwargs):

ibis/backends/sql/__init__.py
123:    def _to_sql(self, expr: ir.Expr, **kwargs) -> str:

ibis/backends/flink/__init__.py
336:    def _to_sql(self, expr: ir.Expr, **kwargs: Any) -> str:
```

File: ibis/expr/sql.py [hunk 3]
```diff
@@ -371,18 +371,17 @@ def to_sql(
...
         except AttributeError:
             raise ValueError(f"Unknown dialect {dialect}")
         else:
-            read = write = getattr(backend, "dialect", dialect)
+            dialect = getattr(backend, "dialect", dialect)
 
-    sql = backend._to_sql(expr.unbind(), **kwargs)
-    (transpiled,) = sg.transpile(sql, read=read, write=write, pretty=pretty)
-    return SQLString(transpiled)
+    sg_expr = backend._to_sqlglot(expr.unbind(), **kwargs)
```
Comment (kszucs) [inline ibis/expr/sql.py:385]: I think this should rather be `backend.compile(expr.unbind(), **kwargs)`

Comment (kszucs) [reply ibis/expr/sql.py:385]: And the backend could be chosen given the `dialect`.

Comment (kszucs) [reply ibis/expr/sql.py:385]: After a second thought, changing it would align with the ibis backends, but if we want to support all dialects in sqlglot then it shouldn't be changed.

File: ibis/backends/__init__.py (hunk 2 above)
Comment (kszucs) [reply ibis/backends/__init__.py:929]: I think removing the `transpile()` surfaced an issue in the compiler:

BEFORE TRANSPILE

```py
Select(
  expressions=[
    Alias(
      this=In(
        this=Column(
          this=Identifier(this=x, quoted=True),
          table=Identifier(this=t0, quoted=True)),
        expressions=[  # here is the difference
          Select(
            expressions=[
              Column(
                this=Identifier(this=x, quoted=True),
                table=Identifier(this=t0, quoted=True))],
            from=From(
              this=Table(
                this=Identifier(this=t, quoted=True),
                alias=Identifier(this=t0, quoted=True))),
            where=Where(
              this=GT(
                this=Column(
                  this=Identifier(this=x, quoted=True),
                  table=Identifier(this=t0, quoted=True)),
                expression=Literal(this=2, is_string=False))))]),
      alias=Identifier(this=InSubquery(x), quoted=True))],
  from=From(
    this=Table(
      this=Identifier(this=t, quoted=True),
      alias=Identifier(this=t0, quoted=True))))
```

AFTER TRANSPILE: 

```py
Select(
  expressions=[
    Alias(
      this=In(
        this=Column(
          this=Identifier(this=x, quoted=True),
          table=Identifier(this=t0, quoted=True)),
        query=Select(  # here is the difference
          expressions=[
            Column(
              this=Identifier(this=x, quoted=True),
              table=Identifier(this=t0, quoted=True))],
          from=From(
            this=Table(
              this=Identifier(this=t, quoted=True),
              alias=TableAlias(
                this=Identifier(this=t0, quoted=True)))),
          where=Where(
            this=GT(
              this=Column(
                this=Identifier(this=x, quoted=True),
                table=Identifier(this=t0, quoted=True)),
              expression=Literal(this=2, is_string=False))))),
      alias=Identifier(this=InSubquery(x), quoted=True))],
  from=From(
    this=Table(
      this=Identifier(this=t, quoted=True),
      alias=TableAlias(
        this=Identifier(this=t0, quoted=True)))))
```

Comment (kszucs) [reply ibis/backends/__init__.py:929]: Here is the fix:

```diff
diff --git a/ibis/backends/sql/compiler.py b/ibis/backends/sql/compiler.py
index e32ff028c..a929e2afc 100644
--- a/ibis/backends/sql/compiler.py
+++ b/ibis/backends/sql/compiler.py
@@ -925,7 +925,7 @@ class SQLGlotCompiler(abc.ABC):
         return self.f.exists(select)

     def visit_InSubquery(self, op, *, rel, needle):
-        return needle.isin(rel.this)
+        return needle.isin(query=rel.this)

     def visit_Array(self, op, *, exprs):
         return self.f.array(*exprs)
```

File: ibis/expr/sql.py (hunk 3 above)
Comment (cpcloud) [reply ibis/expr/sql.py:385]: I think we can visit changing it in a follow-up if we do it at all. I'm inclined to leave compile returning strings for now.

File: ibis/backends/__init__.py (hunk 2 above)
Comment (cpcloud) [reply ibis/backends/__init__.py:929]: Thanks, should cut down on the snapshot changes too.

File: ibis/backends/tests/snapshots/test_sql/test_isin_bug/clickhouse/out.sql (hunk 1 above)
[the remark this answers is not in the document]
Comment (cpcloud) [reply ibis/backends/tests/snapshots/test_sql/test_isin_bug/clickhouse/out.sql:2]: Fixed by your diff from another comment.

**Comment by cpcloud** [comment]
Running the cloud tests locally since BigQuery CI takes over an hour to run.

**Comment by cpcloud** [comment]
Cloud tests are passing:

```
…/ibis on  bump-sqlglot is 📦 v8.0.0 via 🐍 v3.12.2 via ❄️   impure (ibis-3.12.2-env)
❯ pytest -m 'bigquery or snowflake' -n auto --dist loadgroup --snapshot-update -q
bringing up nodes...
..............................................................x....................................x...x.....xx...x........x.x......x.x...........x...x..xx..xxx.....x..........x.....x...x... [  5%]
..........x.xx..x......................................x....x..x........xx..........xx...xx.......xx.x..xx............x....x...x..x...x.............xxx..............................xx..x...x [ 11%]
...x....x.......x..x.......x..........................xx..x.....................x......x...x.xx..x..x.xx.......................................x.............................................. [ 16%]
.......x..........................................s........x.................x....x...............xx.........x...x...x.......x...xx..x...............s.........................xx.x..........x [ 22%]
................x........x...........................x..............x...xx......x.......x.....x......x.........................................x.x......x.......x................x...x.......x [ 28%]
......................xxx..................x......x......x..............xx..........x.x.....................xx..x...xxxxx.xxxxx.sx.......xx...xxxx.xxx..x.......xx......x...........x..x...x.. [ 33%]
........................x.....xx................................x......x...x...xxxx.........x..............x......x...x.............x.......x.xx......x...xx......xx..........x...x.....x..... [ 39%]
.............x..............x..................x...........x.....x....ssssssssssssssssssssssx...x..........xx...x...x......xxx...x..x.............x...........xx.............................x [ 45%]
........x.x.x.......x...x......x.........x...xxx.x.x..x.x.......x.....x....x.........x.x........x....x..........................xx....x....x.....x.x..................x...x..............x.... [ 50%]
....x..x..x...............................................x.xx.....x..x.x..x...........x.........x.....x...x..x..........x.x.x...x.....x..x.....x........x.x.........xx.x..x..x..x.x..xx....xx [ 56%]
................................xx....x...................................................................s...........s......x..x..s.....s...x...x.x...........xx..x.x...x...xx............... [ 62%]
.x..............x....x...x...................x..s.....................x...x......xx.x..x...........xx............xx....x........xxxx.....x........x...........x....x......x.......x..........x [ 67%]
.xxx.x.x.x..xx.x........x...........x.......................................................x.x..x..............................................................................xxxxxxxxx.xx.. [ 73%]
....xxx.xxxxx...x.x...x.xxx..x.xxxx.xxxxxx.xxxx...xxx.xx..x..x.x...x.x.x.x.......x.x...xxx..xx.xxx.x.xxxx.xxxxxxxxxx.xxx...x.x...xxx........x...x...........x......x......x..x...x............ [ 79%]
..xx.................x........x........x...x....x...x......x...xx...x.x.........x...................x......x.........x............x........................x.................................. [ 84%]
...................................x.......................................................................................................................................................... [ 90%]
........................................x........................................................................................................................................x............ [ 96%]
....................................................................................................sException ignored in: <socket.socket fd=16, family=2, type=1, proto=6, laddr=('192.168.50.72', 51904), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=16, family=2, type=1, proto=6, laddr=('192.168.50.72', 51904), raddr=('34.102.189.10', 443)>
..Exception ignored in: <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 51936), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 51936), raddr=('34.102.189.10', 443)>
....Exception ignored in: <socket.socket fd=16, family=2, type=1, proto=6, laddr=('192.168.50.72', 51980), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=16, family=2, type=1, proto=6, laddr=('192.168.50.72', 51980), raddr=('34.102.189.10', 443)>
....Exception ignored in: <socket.socket fd=17, family=2, type=1, proto=6, laddr=('192.168.50.72', 52026), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=17, family=2, type=1, proto=6, laddr=('192.168.50.72', 52026), raddr=('34.102.189.10', 443)>
....Exception ignored in: <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 35072), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 35072), raddr=('34.102.189.10', 443)>
Exception ignored in: <socket.socket fd=17, family=2, type=1, proto=6, laddr=('192.168.50.72', 35088), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=17, family=2, type=1, proto=6, laddr=('192.168.50.72', 35088), raddr=('34.102.189.10', 443)>
Exception ignored in: <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 35106), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 35106), raddr=('34.102.189.10', 443)>
Exception ignored in: <socket.socket fd=17, family=2, type=1, proto=6, laddr=('192.168.50.72', 35122), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=17, family=2, type=1, proto=6, laddr=('192.168.50.72', 35122), raddr=('34.102.189.10', 443)>
.Exception ignored in: <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 35126), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 35126), raddr=('34.102.189.10', 443)>
.Exception ignored in: <socket.socket fd=19, family=2, type=1, proto=6, laddr=('192.168.50.72', 35144), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=19, family=2, type=1, proto=6, laddr=('192.168.50.72', 35144), raddr=('34.102.189.10', 443)>
Exception ignored in: <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 35142), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 35142), raddr=('34.102.189.10', 443)>
.....Exception ignored in: <socket.socket fd=32, family=2, type=1, proto=6, laddr=('192.168.50.72', 35198), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=32, family=2, type=1, proto=6, laddr=('192.168.50.72', 35198), raddr=('34.102.189.10', 443)>
.Exception ignored in: <socket.socket fd=32, family=2, type=1, proto=6, laddr=('192.168.50.72', 35204), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=32, family=2, type=1, proto=6, laddr=('192.168.50.72', 35204), raddr=('34.102.189.10', 443)>
Exception ignored in: <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 35226), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 35226), raddr=('34.102.189.10', 443)>
Exception ignored in: <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 35234), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 35234), raddr=('34.102.189.10', 443)>
.Exception ignored in: <socket.socket fd=27, family=2, type=1, proto=6, laddr=('192.168.50.72', 35242), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=27, family=2, type=1, proto=6, laddr=('192.168.50.72', 35242), raddr=('34.102.189.10', 443)>
Exception ignored in: <socket.socket fd=27, family=2, type=1, proto=6, laddr=('192.168.50.72', 35246), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=27, family=2, type=1, proto=6, laddr=('192.168.50.72', 35246), raddr=('34.102.189.10', 443)>
.Exception ignored in: <socket.socket fd=27, family=2, type=1, proto=6, laddr=('192.168.50.72', 35256), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=27, family=2, type=1, proto=6, laddr=('192.168.50.72', 35256), raddr=('34.102.189.10', 443)>
...Exception ignored in: <socket.socket fd=17, family=2, type=1, proto=6, laddr=('192.168.50.72', 44690), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=17, family=2, type=1, proto=6, laddr=('192.168.50.72', 44690), raddr=('34.102.189.10', 443)>
Exception ignored in: <socket.socket fd=32, family=2, type=1, proto=6, laddr=('192.168.50.72', 44700), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=32, family=2, type=1, proto=6, laddr=('192.168.50.72', 44700), raddr=('34.102.189.10', 443)>
Exception ignored in: <socket.socket fd=32, family=2, type=1, proto=6, laddr=('192.168.50.72', 44714), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=32, family=2, type=1, proto=6, laddr=('192.168.50.72', 44714), raddr=('34.102.189.10', 443)>
.Exception ignored in: <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 44730), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=14, family=2, type=1, proto=6, laddr=('192.168.50.72', 44730), raddr=('34.102.189.10', 443)>
.Exception ignored in: <socket.socket fd=27, family=2, type=1, proto=6, laddr=('192.168.50.72', 44736), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=27, family=2, type=1, proto=6, laddr=('192.168.50.72', 44736), raddr=('34.102.189.10', 443)>
Exception ignored in: <socket.socket fd=27, family=2, type=1, proto=6, laddr=('192.168.50.72', 44750), raddr=('34.102.189.10', 443)>
Traceback (most recent call last):
  File "/nix/store/lw9wd3vvhipidiik52px4q7my8463nin-python3-3.12.2-env/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/poolmanager.py", line 223, in clear
    self.pools.clear()
ResourceWarning: unclosed <socket.socket fd=27, family=2, type=1, proto=6, laddr=('192.168.50.72', 44750), raddr=('34.102.189.10', 443)>
..                                                           [100%]
2907 passed, 31 skipped, 424 xfailed in 472.68s (0:07:52)
```
